---

# Check to make sure that we have the NFD git repo still downloaded
- name: Check for NFD git repo in {{ nfd_download_path }}
  stat:
    path: '{{ nfd_download_path }}'
  register: found_nfd

# If the NFD git repo was found on the system, let the user know it's being deleted
- block:
  - debug:
      msg: 'Found NFD git repo path. Removing it.'

  - file:
      state: absent
      path: '{{ nfd_download_path }}'

  when: found_nfd.stat.exists

# Download/redownload NFD git repo
- debug:
    msg: 'Could not find NFD git repo path'
  when: not found_nfd.stat.exists

- name: Clone NFD git repo
  git:
    repo: 'https://github.com/openshift/cluster-nfd-operator.git'
    dest: '{{ nfd_download_path }}'
    version: 'release-{{ openshift_release }}'
