FROM YOUR-IMAGE-HERE
MAINTAINER Courtney Pacheco <cpacheco@redhat.com>

# Set workspace related vars
ENV SCRIPTS_DIR /home/mnist/src

# Create the directories to setup the workspace
RUN mkdir -p ${SCRIPTS_DIR}
WORKDIR ${SCRIPTS_DIR}

# Pull scripts in so that we can run the MNIST benchmark
COPY src/mnist.py ${SCRIPTS_DIR}
COPY src/main.py ${SCRIPTS_DIR}
COPY src/__init__.py ${SCRIPTS_DIR}
