---

# Check to make sure that we have the SRO git repo still downloaded
- name: Check for SRO git repo in {{ sro_download_path }}
  stat:
    path: '{{ sro_download_path }}'
  register: found_sro

# If the SRO git repo was found on the system, let the user know it's being deleted
- block:
  - debug:
      msg: 'Found SRO git repo path. Removing it.'

  - file:
      state: absent
      path: '{{ sro_download_path }}'

  when: found_sro.stat.exists

# Download/redownload SRO git repo
- debug:
    msg: 'Could not find SRO git repo path'
  when: not found_sro.stat.exists

- name: Clone SRO git repo
  git:
    repo: 'https://github.com/openshift-psap/special-resource-operator.git'
    dest: '{{ sro_download_path }}'
    version: 'release-{{ openshift_release }}'
